// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0wmd_l-qy1YgqVA81MPy06uF6KrqOkMk',
    appId: '1:589748539279:web:efb4e340d904a0fc7cc5fa',
    messagingSenderId: '589748539279',
    projectId: 'getx-login-30458',
    authDomain: 'getx-login-30458.firebaseapp.com',
    storageBucket: 'getx-login-30458.appspot.com',
    measurementId: 'G-G0GTD1S2DW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7L9cyRNWvvECFUdvjQi3MFnMxz0N8Mrw',
    appId: '1:589748539279:android:3054b6d3e00353ed7cc5fa',
    messagingSenderId: '589748539279',
    projectId: 'getx-login-30458',
    storageBucket: 'getx-login-30458.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGSthZktN24z9ARrg4ffI2P6fDY67sQEI',
    appId: '1:589748539279:ios:b9c8edaa4a1c33027cc5fa',
    messagingSenderId: '589748539279',
    projectId: 'getx-login-30458',
    storageBucket: 'getx-login-30458.appspot.com',
    iosClientId: '589748539279-mehlnch715ltkus5ovfm0kdq7l5kho25.apps.googleusercontent.com',
    iosBundleId: 'com.example.getxLoginLecture',
  );
}
